export type ExpertiseLevel = "INTERN" | "ENTRY" | "MID" | "SENIOR" | "LEAD" | "PRINCIPAL" | "EXECUTIVE";
export type Availability = "OPEN" | "PASSIVE" | "NOT_LOOKING";

export type MockCandidate = {
  id: string;
  displayName: string;
  headline: string;
  bio: string;
  location: string;
  photoUrl: null;
  expertiseLevel: ExpertiseLevel;
  availabilityStatus: Availability;
  openToRemote: boolean;
  openToRelocation: boolean;
  yearsExperience: number;
  careerField: { name: string; slug: string; icon: string };
  skills: { skill: { name: string }; level: string }[];
  workExperiences: { title: string; company: string; startDate: string; endDate: string | null; current: boolean; description: string }[];
  educations: { institution: string; degree: string; field: string; startYear: number; endYear: number | null }[];
};

export type CareerField = {
  id: string;
  name: string;
  slug: string;
  icon: string;
  parentId: null;
};

export const CAREER_FIELDS: CareerField[] = [
  { id: "1", name: "Software Engineering", slug: "software-engineering", icon: "💻", parentId: null },
  { id: "2", name: "Data & Analytics", slug: "data-analytics", icon: "📊", parentId: null },
  { id: "3", name: "Design", slug: "design", icon: "🎨", parentId: null },
  { id: "4", name: "Product Management", slug: "product-management", icon: "🗺️", parentId: null },
  { id: "5", name: "Marketing", slug: "marketing", icon: "📣", parentId: null },
  { id: "6", name: "Sales", slug: "sales", icon: "🤝", parentId: null },
  { id: "7", name: "Finance & Accounting", slug: "finance-accounting", icon: "💰", parentId: null },
  { id: "8", name: "Operations", slug: "operations", icon: "⚙️", parentId: null },
  { id: "9", name: "Human Resources", slug: "human-resources", icon: "👥", parentId: null },
  { id: "10", name: "Customer Success", slug: "customer-success", icon: "⭐", parentId: null },
  { id: "11", name: "Healthcare", slug: "healthcare", icon: "🏥", parentId: null },
  { id: "12", name: "Trades & Skilled Labor", slug: "trades-skilled-labor", icon: "🔧", parentId: null },
];

export const MOCK_CANDIDATES: MockCandidate[] = [
  {
    id: "c1",
    displayName: "Alex Rivera",
    headline: "Senior Full-Stack Engineer · React, Node.js, PostgreSQL",
    bio: "I build scalable web products end-to-end. I've led engineering at two YC-backed startups and love working on teams that ship fast without cutting corners. Strong opinions on code quality, loosely held.",
    location: "San Francisco, CA",
    photoUrl: null,
    expertiseLevel: "SENIOR",
    availabilityStatus: "OPEN",
    openToRemote: true,
    openToRelocation: false,
    yearsExperience: 7,
    careerField: { name: "Software Engineering", slug: "software-engineering", icon: "💻" },
    skills: [
      { skill: { name: "React" }, level: "EXPERT" },
      { skill: { name: "TypeScript" }, level: "EXPERT" },
      { skill: { name: "Node.js" }, level: "ADVANCED" },
      { skill: { name: "PostgreSQL" }, level: "ADVANCED" },
      { skill: { name: "AWS" }, level: "INTERMEDIATE" },
    ],
    workExperiences: [
      { title: "Senior Software Engineer", company: "Stripe", startDate: "2021-03-01", endDate: null, current: true, description: "Built and maintained payment reconciliation infrastructure processing $2B/day." },
      { title: "Software Engineer", company: "Notion", startDate: "2019-06-01", endDate: "2021-02-28", current: false, description: "Worked on the real-time collaboration layer for the editor." },
    ],
    educations: [{ institution: "UC Berkeley", degree: "B.S.", field: "Computer Science", startYear: 2014, endYear: 2018 }],
  },
  {
    id: "c2",
    displayName: "Priya Nair",
    headline: "ML Engineer · LLMs, PyTorch, Production AI Systems",
    bio: "I specialize in taking ML models from research to production. Currently focused on large language model fine-tuning and evaluation pipelines. Looking for a role where AI is core, not a side project.",
    location: "New York, NY",
    photoUrl: null,
    expertiseLevel: "MID",
    availabilityStatus: "OPEN",
    openToRemote: true,
    openToRelocation: true,
    yearsExperience: 4,
    careerField: { name: "Data & Analytics", slug: "data-analytics", icon: "📊" },
    skills: [
      { skill: { name: "Python" }, level: "EXPERT" },
      { skill: { name: "PyTorch" }, level: "EXPERT" },
      { skill: { name: "Machine Learning" }, level: "ADVANCED" },
      { skill: { name: "SQL" }, level: "ADVANCED" },
      { skill: { name: "Spark" }, level: "INTERMEDIATE" },
    ],
    workExperiences: [
      { title: "ML Engineer", company: "Cohere", startDate: "2022-07-01", endDate: null, current: true, description: "Fine-tuned and evaluated language models for enterprise customers." },
      { title: "Data Scientist", company: "Shopify", startDate: "2020-09-01", endDate: "2022-06-30", current: false, description: "Built recommendation systems driving 15% revenue lift." },
    ],
    educations: [{ institution: "University of Toronto", degree: "M.Sc.", field: "Machine Learning", startYear: 2018, endYear: 2020 }],
  },
  {
    id: "c3",
    displayName: "Jordan Kim",
    headline: "Product Designer · Design Systems, 0→1, Figma",
    bio: "I design products that feel obvious in retrospect. I've built design systems from scratch at two Series B companies and thrive in the 0→1 phase. I care deeply about accessibility and write my own code when needed.",
    location: "Austin, TX",
    photoUrl: null,
    expertiseLevel: "SENIOR",
    availabilityStatus: "PASSIVE",
    openToRemote: true,
    openToRelocation: false,
    yearsExperience: 6,
    careerField: { name: "Design", slug: "design", icon: "🎨" },
    skills: [
      { skill: { name: "Figma" }, level: "EXPERT" },
      { skill: { name: "Prototyping" }, level: "EXPERT" },
      { skill: { name: "User Research" }, level: "ADVANCED" },
      { skill: { name: "React" }, level: "INTERMEDIATE" },
    ],
    workExperiences: [
      { title: "Staff Product Designer", company: "Linear", startDate: "2022-01-01", endDate: null, current: true, description: "Own the design system and lead design across the core product." },
      { title: "Senior Product Designer", company: "Figma", startDate: "2019-04-01", endDate: "2021-12-31", current: false, description: "Designed the multiplayer cursor and commenting features." },
    ],
    educations: [{ institution: "RISD", degree: "B.F.A.", field: "Graphic Design", startYear: 2013, endYear: 2017 }],
  },
  {
    id: "c4",
    displayName: "Marcus Webb",
    headline: "Senior Product Manager · B2B SaaS, Growth, Data-Driven",
    bio: "I turn ambiguous problems into clear roadmaps and ship products that actually move the needle. Former founder, so I understand what it means to own outcomes end-to-end. Great at working with both engineers and executives.",
    location: "Seattle, WA",
    photoUrl: null,
    expertiseLevel: "SENIOR",
    availabilityStatus: "OPEN",
    openToRemote: false,
    openToRelocation: false,
    yearsExperience: 8,
    careerField: { name: "Product Management", slug: "product-management", icon: "🗺️" },
    skills: [
      { skill: { name: "Agile / Scrum" }, level: "EXPERT" },
      { skill: { name: "SQL" }, level: "ADVANCED" },
      { skill: { name: "User Research" }, level: "ADVANCED" },
      { skill: { name: "Communication" }, level: "EXPERT" },
    ],
    workExperiences: [
      { title: "Senior PM", company: "Salesforce", startDate: "2021-08-01", endDate: null, current: true, description: "Owned the AI features roadmap for Sales Cloud, $400M ARR product." },
      { title: "Product Manager", company: "Twilio", startDate: "2018-05-01", endDate: "2021-07-31", current: false, description: "Launched Twilio Verify, now used by 400K developers." },
    ],
    educations: [{ institution: "Stanford University", degree: "M.B.A.", field: "Business", startYear: 2015, endYear: 2017 }],
  },
  {
    id: "c5",
    displayName: "Sofia Martinez",
    headline: "Frontend Engineer · Vue.js, Performance, Design Systems",
    bio: "I obsess over the gap between design and implementation — I want the pixels to be pixel-perfect and the interactions to feel alive. I've built component libraries used by 100+ engineers.",
    location: "Miami, FL",
    photoUrl: null,
    expertiseLevel: "MID",
    availabilityStatus: "OPEN",
    openToRemote: true,
    openToRelocation: true,
    yearsExperience: 3,
    careerField: { name: "Software Engineering", slug: "software-engineering", icon: "💻" },
    skills: [
      { skill: { name: "Vue.js" }, level: "EXPERT" },
      { skill: { name: "TypeScript" }, level: "ADVANCED" },
      { skill: { name: "Tailwind CSS" }, level: "EXPERT" },
      { skill: { name: "JavaScript" }, level: "EXPERT" },
      { skill: { name: "Figma" }, level: "INTERMEDIATE" },
    ],
    workExperiences: [
      { title: "Frontend Engineer", company: "GitLab", startDate: "2022-03-01", endDate: null, current: true, description: "Built and maintained the Vue 3 component library used across GitLab's product." },
      { title: "Junior Frontend Engineer", company: "Netlify", startDate: "2021-01-01", endDate: "2022-02-28", current: false, description: "Worked on the Deploy Previews and CI dashboard UI." },
    ],
    educations: [{ institution: "Florida International University", degree: "B.S.", field: "Computer Science", startYear: 2017, endYear: 2021 }],
  },
  {
    id: "c6",
    displayName: "Devon Clarke",
    headline: "Growth Marketing Lead · SEO, Paid Acquisition, Analytics",
    bio: "I've grown SaaS products from 0 to 50K users through a mix of content, SEO, and paid channels. Data-driven to the core — I don't run experiments I can't measure.",
    location: "Chicago, IL",
    photoUrl: null,
    expertiseLevel: "LEAD",
    availabilityStatus: "PASSIVE",
    openToRemote: true,
    openToRelocation: false,
    yearsExperience: 7,
    careerField: { name: "Marketing", slug: "marketing", icon: "📣" },
    skills: [
      { skill: { name: "SEO / SEM" }, level: "EXPERT" },
      { skill: { name: "SQL" }, level: "INTERMEDIATE" },
      { skill: { name: "Communication" }, level: "ADVANCED" },
      { skill: { name: "Tableau" }, level: "INTERMEDIATE" },
    ],
    workExperiences: [
      { title: "Head of Growth", company: "Loom", startDate: "2020-11-01", endDate: null, current: true, description: "Scaled organic from 50K to 500K monthly sessions. Managed $2M paid budget." },
      { title: "Senior SEO Manager", company: "HubSpot", startDate: "2018-02-01", endDate: "2020-10-31", current: false, description: "Grew the HubSpot Blog to 8M monthly readers." },
    ],
    educations: [{ institution: "Northwestern University", degree: "B.A.", field: "Communications", startYear: 2012, endYear: 2016 }],
  },
  {
    id: "c7",
    displayName: "Tyler Okonkwo",
    headline: "DevOps / Platform Engineer · Kubernetes, Terraform, AWS",
    bio: "I build the infrastructure that lets product teams ship faster. I care about developer experience as much as reliability — great DX is a force multiplier. Comfortable owning infra solo or leading a platform team.",
    location: "Atlanta, GA",
    photoUrl: null,
    expertiseLevel: "SENIOR",
    availabilityStatus: "OPEN",
    openToRemote: true,
    openToRelocation: false,
    yearsExperience: 6,
    careerField: { name: "Software Engineering", slug: "software-engineering", icon: "💻" },
    skills: [
      { skill: { name: "Kubernetes" }, level: "EXPERT" },
      { skill: { name: "Terraform" }, level: "EXPERT" },
      { skill: { name: "AWS" }, level: "EXPERT" },
      { skill: { name: "Docker" }, level: "EXPERT" },
      { skill: { name: "Go" }, level: "ADVANCED" },
    ],
    workExperiences: [
      { title: "Staff Platform Engineer", company: "Datadog", startDate: "2020-06-01", endDate: null, current: true, description: "Built and maintains the internal deployment platform used by 800+ engineers." },
      { title: "DevOps Engineer", company: "Docker", startDate: "2018-04-01", endDate: "2020-05-31", current: false, description: "Maintained CI/CD infrastructure for the Docker Hub product." },
    ],
    educations: [{ institution: "Georgia Tech", degree: "B.S.", field: "Computer Engineering", startYear: 2013, endYear: 2017 }],
  },
  {
    id: "c8",
    displayName: "Yuki Tanaka",
    headline: "Data Engineer · dbt, Airflow, Snowflake, Real-Time Pipelines",
    bio: "I build data infrastructure that analysts actually trust. Strong opinions on data modeling, documentation, and testing. I've built data platforms from the ground up at two fintech companies.",
    location: "Los Angeles, CA",
    photoUrl: null,
    expertiseLevel: "MID",
    availabilityStatus: "OPEN",
    openToRemote: true,
    openToRelocation: true,
    yearsExperience: 4,
    careerField: { name: "Data & Analytics", slug: "data-analytics", icon: "📊" },
    skills: [
      { skill: { name: "dbt" }, level: "EXPERT" },
      { skill: { name: "SQL" }, level: "EXPERT" },
      { skill: { name: "Python" }, level: "ADVANCED" },
      { skill: { name: "Spark" }, level: "INTERMEDIATE" },
    ],
    workExperiences: [
      { title: "Data Engineer", company: "Brex", startDate: "2021-09-01", endDate: null, current: true, description: "Built real-time transaction monitoring pipelines processing 10M events/day." },
      { title: "Analytics Engineer", company: "Affirm", startDate: "2020-01-01", endDate: "2021-08-31", current: false, description: "Owned the merchant analytics data model." },
    ],
    educations: [{ institution: "UCLA", degree: "B.S.", field: "Statistics", startYear: 2015, endYear: 2019 }],
  },
  {
    id: "c9",
    displayName: "Amara Osei",
    headline: "Account Executive · SaaS Sales, Mid-Market, $500K+ ACV",
    bio: "I close. In my last role I finished 140% of quota and was top AE for 3 consecutive quarters. I love complex, multi-stakeholder deals and I'm not afraid to walk away from bad fits.",
    location: "Boston, MA",
    photoUrl: null,
    expertiseLevel: "SENIOR",
    availabilityStatus: "PASSIVE",
    openToRemote: false,
    openToRelocation: true,
    yearsExperience: 6,
    careerField: { name: "Sales", slug: "sales", icon: "🤝" },
    skills: [
      { skill: { name: "Communication" }, level: "EXPERT" },
      { skill: { name: "Leadership" }, level: "INTERMEDIATE" },
    ],
    workExperiences: [
      { title: "Senior Account Executive", company: "Gong", startDate: "2021-03-01", endDate: null, current: true, description: "Responsible for mid-market accounts $200K–$1.5M ACV. 140% of quota FY2023." },
      { title: "Account Executive", company: "Outreach", startDate: "2019-06-01", endDate: "2021-02-28", current: false, description: "Closed 45 net-new logos in 18 months across financial services vertical." },
    ],
    educations: [{ institution: "Boston University", degree: "B.S.", field: "Business Administration", startYear: 2013, endYear: 2017 }],
  },
  {
    id: "c10",
    displayName: "Cameron Lee",
    headline: "UX Researcher · Mixed Methods, B2C, Qual + Quant",
    bio: "I help teams understand what users actually need, not what they say they need. Specializing in mixed-methods research: contextual inquiry, usability testing, survey design, and analysis. I translate complexity into clear, actionable findings.",
    location: "Portland, OR",
    photoUrl: null,
    expertiseLevel: "MID",
    availabilityStatus: "OPEN",
    openToRemote: true,
    openToRelocation: false,
    yearsExperience: 5,
    careerField: { name: "Design", slug: "design", icon: "🎨" },
    skills: [
      { skill: { name: "User Research" }, level: "EXPERT" },
      { skill: { name: "Figma" }, level: "INTERMEDIATE" },
      { skill: { name: "Communication" }, level: "EXPERT" },
    ],
    workExperiences: [
      { title: "UX Researcher", company: "Spotify", startDate: "2021-06-01", endDate: null, current: true, description: "Led foundational research for Spotify's podcast discovery experience, used by 60M+ listeners." },
      { title: "UX Researcher", company: "Airbnb", startDate: "2019-08-01", endDate: "2021-05-31", current: false, description: "Ran 200+ usability sessions on the host onboarding flow." },
    ],
    educations: [{ institution: "University of Oregon", degree: "M.S.", field: "Human-Computer Interaction", startYear: 2016, endYear: 2018 }],
  },
  {
    id: "c11",
    displayName: "Rachel Torres",
    headline: "Backend Engineer · Go, gRPC, Distributed Systems",
    bio: "I build systems that handle scale gracefully. My sweet spot is designing reliable distributed services — I think deeply about failure modes and operational concerns before writing a line of code.",
    location: "Denver, CO",
    photoUrl: null,
    expertiseLevel: "SENIOR",
    availabilityStatus: "OPEN",
    openToRemote: true,
    openToRelocation: false,
    yearsExperience: 8,
    careerField: { name: "Software Engineering", slug: "software-engineering", icon: "💻" },
    skills: [
      { skill: { name: "Go" }, level: "EXPERT" },
      { skill: { name: "PostgreSQL" }, level: "EXPERT" },
      { skill: { name: "Kubernetes" }, level: "ADVANCED" },
      { skill: { name: "Redis" }, level: "ADVANCED" },
      { skill: { name: "REST APIs" }, level: "EXPERT" },
    ],
    workExperiences: [
      { title: "Senior Backend Engineer", company: "Cloudflare", startDate: "2019-10-01", endDate: null, current: true, description: "Builds core DNS resolution infrastructure serving 1T+ queries/day." },
      { title: "Software Engineer", company: "Uber", startDate: "2016-07-01", endDate: "2019-09-30", current: false, description: "Worked on the dispatch system for Uber's APAC markets." },
    ],
    educations: [{ institution: "University of Washington", degree: "B.S.", field: "Computer Science", startYear: 2012, endYear: 2016 }],
  },
  {
    id: "c12",
    displayName: "Noah Ashby",
    headline: "Financial Analyst · FP&A, SaaS Metrics, Board Reporting",
    bio: "I turn financial data into decisions. I'm fluent in SaaS metrics — ARR, NRR, CAC, LTV — and I've built the financial model from scratch at two pre-IPO companies. Strong communicator who makes finance accessible to non-finance people.",
    location: "New York, NY",
    photoUrl: null,
    expertiseLevel: "MID",
    availabilityStatus: "PASSIVE",
    openToRemote: false,
    openToRelocation: false,
    yearsExperience: 4,
    careerField: { name: "Finance & Accounting", slug: "finance-accounting", icon: "💰" },
    skills: [
      { skill: { name: "SQL" }, level: "INTERMEDIATE" },
      { skill: { name: "Tableau" }, level: "ADVANCED" },
      { skill: { name: "Communication" }, level: "ADVANCED" },
    ],
    workExperiences: [
      { title: "Senior Financial Analyst", company: "Ramp", startDate: "2022-02-01", endDate: null, current: true, description: "Owns the operating model and monthly board reporting package." },
      { title: "Financial Analyst", company: "Goldman Sachs", startDate: "2020-07-01", endDate: "2022-01-31", current: false, description: "TMT investment banking coverage." },
    ],
    educations: [{ institution: "NYU Stern", degree: "B.S.", field: "Finance", startYear: 2016, endYear: 2020 }],
  },
  {
    id: "c13",
    displayName: "Destiny Patel",
    headline: "Entry-Level iOS Engineer · Swift, SwiftUI, Xcode",
    bio: "Recent CS grad passionate about mobile development. I built two indie apps with 5K+ combined downloads while in school and love the craft of making things feel native and fast on Apple platforms.",
    location: "Remote",
    photoUrl: null,
    expertiseLevel: "ENTRY",
    availabilityStatus: "OPEN",
    openToRemote: true,
    openToRelocation: true,
    yearsExperience: 1,
    careerField: { name: "Software Engineering", slug: "software-engineering", icon: "💻" },
    skills: [
      { skill: { name: "Swift" }, level: "ADVANCED" },
      { skill: { name: "JavaScript" }, level: "INTERMEDIATE" },
      { skill: { name: "React" }, level: "BEGINNER" },
    ],
    workExperiences: [
      { title: "iOS Engineering Intern", company: "Duolingo", startDate: "2023-05-01", endDate: "2023-08-31", current: false, description: "Shipped the animated streak freeze feature to 40M daily active users." },
    ],
    educations: [{ institution: "Carnegie Mellon University", degree: "B.S.", field: "Computer Science", startYear: 2019, endYear: 2023 }],
  },
  {
    id: "c14",
    displayName: "James Whitfield",
    headline: "Head of People Operations · Recruiting, Culture, Scaling Teams",
    bio: "I've built HR functions from scratch at companies scaling from 20 to 500 people. I believe great recruiting is a product function and great culture is designed, not accidental.",
    location: "San Francisco, CA",
    photoUrl: null,
    expertiseLevel: "LEAD",
    availabilityStatus: "PASSIVE",
    openToRemote: true,
    openToRelocation: false,
    yearsExperience: 9,
    careerField: { name: "Human Resources", slug: "human-resources", icon: "👥" },
    skills: [
      { skill: { name: "Leadership" }, level: "EXPERT" },
      { skill: { name: "Communication" }, level: "EXPERT" },
      { skill: { name: "Project Management" }, level: "ADVANCED" },
    ],
    workExperiences: [
      { title: "Head of People", company: "Scale AI", startDate: "2021-01-01", endDate: null, current: true, description: "Built the recruiting function that scaled Scale AI from 180 to 650 employees." },
      { title: "Senior HR Business Partner", company: "Lyft", startDate: "2017-09-01", endDate: "2020-12-31", current: false, description: "Supported Engineering org of 600+ across the IPO and beyond." },
    ],
    educations: [{ institution: "UC Santa Barbara", degree: "B.A.", field: "Psychology", startYear: 2009, endYear: 2013 }],
  },
  {
    id: "c15",
    displayName: "Elena Sokolova",
    headline: "Security Engineer · AppSec, Penetration Testing, Cloud Security",
    bio: "I find the holes before the bad guys do. I've led red-team exercises and built secure development programs at fintech and healthtech companies. I believe security should enable engineering, not block it.",
    location: "Washington, DC",
    photoUrl: null,
    expertiseLevel: "SENIOR",
    availabilityStatus: "OPEN",
    openToRemote: true,
    openToRelocation: false,
    yearsExperience: 7,
    careerField: { name: "Software Engineering", slug: "software-engineering", icon: "💻" },
    skills: [
      { skill: { name: "Python" }, level: "ADVANCED" },
      { skill: { name: "AWS" }, level: "ADVANCED" },
      { skill: { name: "Go" }, level: "INTERMEDIATE" },
    ],
    workExperiences: [
      { title: "Staff Security Engineer", company: "Capital One", startDate: "2020-05-01", endDate: null, current: true, description: "Leads the cloud security posture management program across AWS and GCP." },
      { title: "Security Engineer", company: "Palo Alto Networks", startDate: "2017-08-01", endDate: "2020-04-30", current: false, description: "Penetration testing and vulnerability research." },
    ],
    educations: [{ institution: "George Mason University", degree: "B.S.", field: "Cybersecurity Engineering", startYear: 2013, endYear: 2017 }],
  },
];
